package observability

const (
	EventContentContinentLoaded             = "content.continent.loaded"
	EventContentContinentValidationFailed   = "content.continent.validation_failed"
	EventContentZoneTransitionLoaded        = "content.zone.transition_loaded"
	EventContentZoneAdjacencyLoaded         = "content.zone.adjacency_loaded"
	EventWorldContinentActivated            = "world.continent.activated"
	EventWorldContinentActivationFailed     = "world.continent.activation_failed"
	EventWorldZoneRuntimeCreated            = "world.zone.runtime_created"
	EventWorldZoneTransitionRequested       = "world.zone.transition_requested"
	EventWorldZoneTransitionCompleted       = "world.zone.transition_completed"
	EventWorldZoneTransitionRejected        = "world.zone.transition_rejected"
	EventWorldZoneEntered                   = "world.zone.entered"
	EventWorldZoneExited                    = "world.zone.exited"
	EventWorldZoneRoutingUpdated            = "world.zone.routing_updated"
	EventWorldCharacterZoneSaved            = "world.character_zone_saved"
	EventWorldCharacterZoneRestored         = "world.character_zone_restored"
	EventWorldCharacterZoneRestoreCorrected = "world.character_zone_restore_corrected"
	EventWorldVisibilityEvaluated           = "world.visibility.evaluated"
	EventWorldVisibilityEntityEntered       = "world.visibility.entity_entered"
	EventWorldVisibilityEntityExited        = "world.visibility.entity_exited"
	EventWorldStreamingHintEmitted          = "world.streaming.hint_emitted"
	EventLoadsimDawnwakeStarted             = "loadsim.dawnwake.started"
	EventLoadsimDawnwakeCompleted           = "loadsim.dawnwake.completed"
)
